# SITE CONFIGURATION
title: Blog jcorpus
author: jcorpus
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://abig.app/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://twitter.com/jsuproc
    - https://www.facebook.com/jsuproc
    - https://www.linkedin.com/in/juliocorpusmechato
    - https://plus.google.com/+juliocorpus
    - https://github.com/jcorpus
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Blog de noticias y más :D

hero_img: /assets/img/icons/background-abig.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: julio@abig.app # email for form submission

twitter_username: jsuproc # replace with your_twitter_username or comment to remove link from footer
github_username:  jcorpus # replace with your_github_username or comment to remove link from footer
instagram_username: jsuproc # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: juliocorpus # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
